version: '3'
services:
  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./web:/var/www/html
    restart: unless-stopped
    environment:
      - FLAG=acsctf{realistic_php_obj_injection_ftw}
